version: '3.8'

services:
    dev:
        container_name: solomon-vision-api
        image: punparin/solomon-vision-api:local
        env_file:
            - .env
        volumes:
            - ./config.json:/app/config.json
        ports:
            - 8080:8080
        restart: unless-stopped
